services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: flightuser
      POSTGRES_PASSWORD: flightpass
      POSTGRES_DB: flightdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data    # ← НОВЕ
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flightuser -d flightdb"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://flightuser:flightpass@db:5432/flightdb
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/app:/code/app
volumes:                # ← ось ця секція, у самому низу
  postgres_data:
